### PR TITLE
Upgrade rocket to 0.4.0

### PR DESCRIPTION
**Pull request by jaysonsantos**
I've updated rocket together with the template system but as there are no tests and I cannot be 100% that I didn't break anything, I also ran
clippy and tried to fix some of the problems.
Let me know if I can do something else.

### CODE REVIEW

**Comment by messense** [comment]
Awesome work!

**Comment by flavray** [comment]
That looks great!
However when checking out your branch and running it locally, I'm getting 404s for all the endpoints with a `timestamp` query parameter :(
This happens for every pages that is not `/clusters`, so seems a bit unfortunate.

Screen Shot 2019-03-31 at 4 11 12 PM

Screen Shot 2019-03-31 at 4 32 39 PM


From the logs, I can see:
```
2019-03-31 16:11:04+0100: (unknown) INFO - _ - Matched: GET /api/clusters/<cluster_id>/topics?<timestamp> (cluster_topics)
2019-03-31 16:11:04+0100: (unknown) WARN - _ - Missing required query parameter 'timestamp'.
2019-03-31 16:11:04+0100: (unknown) INFO - _ - Outcome: Forward
2019-03-31 16:11:04+0100: (unknown) ERROR - _ - No matching routes for GET /api/clusters/local_cluster/topics?_=1554045064380 application/json.
2019-03-31 16:11:04+0100: (unknown) WARN - _ - Responding with 404 Not Found catcher.
```


I tried removing the `timestamp` field (which is never used, but present only because datatable sends a `?_=<timestamp>` with every ajax request) from all the endpoints and it seems to solve the issue. (diff [here](https://pastebin.com/NsCgD5af)).

I've had a look at the [breaking changes](https://github.com/SergioBenitez/Rocket/blob/v0.4.0/CHANGELOG.md#breaking-changes) in rocket, but could not find anything that stood out though.

Are you getting the same errors?

**Comment by jaysonsantos** [comment]
Hey there, it should be fixed now.
To work, the parameter would have to be called timestamp=15... instead of _=15... and as I saw as it was being ignored everywhere, I just removed from the route and it worked fine.

**Comment by jaysonsantos** [comment]
Sorry, I just read that you said exactly that `I tried removing the timestamp field (which is never used, but present only because datatable sends a ?_=<timestamp> with every ajax request) from all the endpoints and it seems to solve the issue. (diff here).`.
When this gets merged I will try to upgrade the other dependencies if you are interested. And if you want, upgrade it to rust 2018.

**Comment by flavray** [comment]
Tested locally and it now works perfectly. Thank you!

**Pull request merged**
